services:
  - type: web
    name: izumi-md
    repo: https://github.com/Akshay-Eypz/izumi-bot
    branch: main
    env: docker
    dockerfilePath: lib/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        required: true
      - key: PREFIX
        sync: false
        required: false
      - key: SUDO
        sync: false
        required: false
      - key: MODE
        sync: false
        required: false
      - key: PORT
        sync: false
        required: true
      - key: RENDER_API_KEY
        sync: false
        required: false
      - key: RENDER_SERVICE_ID
        sync: false
        required: false
      - key: DATABASE_URL
        sync: false
        required: false
